In [1]:
#张量
import torch

In [2]:
a=[1,2,3]

In [3]:
type(a)

list

In [4]:
b=torch.tensor(a)

In [5]:
type(b)

torch.Tensor

In [7]:
b.dtype

torch.int64

In [9]:
import numpy as np

In [20]:
c=np.random.normal((2,3))

In [21]:
d= torch.tensor(c)

In [22]:
e=torch.zeros_like(d)#形状数据类型保持一致

In [23]:
e

tensor([0., 0.], dtype=torch.float64)

In [ ]:
#rand_like
#zero_like
#ones_like

In [27]:
f=torch.rand((2,3))

Attribute

In [28]:
f.dtype

torch.float32

In [29]:
f.shape

torch.Size([2, 3])

In [30]:
f.device

device(type='cpu')

Operation

In [31]:
torch.cuda.is_available()

False

In [32]:
f

tensor([[0.9121, 0.3921, 0.9600],
        [0.6555, 0.9606, 0.2792]])

In [33]:
torch.is_tensor(f)

True

In [37]:
torch.zeros((5,5),dtype=torch.int32)

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]], dtype=torch.int32)

In [35]:
#set_default_tensor_type

In [ ]:
#arange range

arange

In [38]:
torch.arange(5)

tensor([0, 1, 2, 3, 4])

In [42]:
torch.arange(0,5,2)

tensor([0, 2, 4])

range

In [44]:
torch.range(0,5)

/var/folders/k6/h8qrbfys4xs6b1b306p8g2wm0000gn/T/ipykernel_38517/1393396694.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,5)


tensor([0., 1., 2., 3., 4., 5.])

eye

In [46]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [47]:
torch.full([2,2],5)

tensor([[5, 5],
        [5, 5]])

cat

In [48]:
a=torch.rand([2,2])
b=torch.rand([2,3])
torch.cat([a,b],dim=1)

tensor([[0.2484, 0.0335, 0.0766, 0.7250, 0.8098],
        [0.2333, 0.1671, 0.9412, 0.8836, 0.6479]])

chuck

In [49]:
b

tensor([[0.0766, 0.7250, 0.8098],
        [0.9412, 0.8836, 0.6479]])

In [53]:
torch.chunk(b,chunks=2)

(tensor([[0.0766, 0.7250, 0.8098]]), tensor([[0.9412, 0.8836, 0.6479]]))

gather(#important)

In [57]:
b

tensor([[0.0766, 0.7250, 0.8098],
        [0.9412, 0.8836, 0.6479]])

In [58]:
torch.gather(b,1,torch.tensor([[1,0],[1,1]]))

tensor([[0.7250, 0.0766],
        [0.8836, 0.8836]])

reshape

In [59]:
# scatter_  写入 scatter_add


Split（特别注意维度相加个数因同其保持相同）

In [ ]:
#squeeze 移除维度为一的维度，dim参数

In [60]:
#stack函数
a=torch.rand([3,2])

In [61]:
b=torch.rand([3,2])

In [65]:
torch.stack([a,b],dim=1)

tensor([[[0.3358, 0.2069],
         [0.1066, 0.0109]],

        [[0.9293, 0.7335],
         [0.7838, 0.8736]],

        [[0.2827, 0.6452],
         [0.7025, 0.8216]]])

Dtype

In [66]:
#Take函数 接受input：tensor index：tensor
#制定函数为铺平一维

In [68]:
#tile函数
#主要起拷贝作用，dim：在某个维度进行

a=torch.rand(4,3)
a_tiled=torch.tile(a,[1,2])

In [69]:
a_tiled

tensor([[0.0637, 0.4711, 0.1562, 0.0637, 0.4711, 0.1562],
        [0.7952, 0.4055, 0.8628, 0.7952, 0.4055, 0.8628],
        [0.9553, 0.0967, 0.3818, 0.9553, 0.0967, 0.3818],
        [0.6170, 0.9249, 0.5779, 0.6170, 0.9249, 0.5779]])

In [ ]:
#transpose函数 转置函数 参数为：dim1，dim2

In [ ]:
#unbind 移除某一个维度，在某一个维度进行tensor分解

In [ ]:
#unsqueeze 添加以为

In [ ]:
#where 判断语句，依据condition进行判断 where（condition，tensor1，tensor2）
#randn，高斯分布
#rand,均匀分布【0，1】

In [70]:
#seed随机数种子、
torch.manual_seed(100)

In [ ]:
#torch.bernoulli(tensor)  采样获取同tensor相同结构的tensor，该tensor全为0，1
#torch.normal 可以更改mean，std的值，size的值
#rand（均匀分布），randint（整数，low，high），randn（高斯分布）（标准分布）
#randperm（随机组合）